### ISSUE TITLE
No deployment file gets created for OpenFaas

### ISSUE THREAD

**Issue by psoares** [micronaut-projects/micronaut-examples#12]
When creating a function with the OpenFaas cli, by default, several artifacts get generated:

* A yml file describing the function
* A directory containing among other things the Dockerfile

e.g.: 
```
faas new myfunction --lang dockerfile
``` 

Produces:
```
myfunction.yml
myfunction/
    Dockerfile
```

When using the micronaut cli, the yml file isn't created, leaving the developer no easy means of deploying the function to OpenFaas.

e.g.:
```
mn create-function myfunction --features openfaas
```
creates the directory with the Dockerfile, but no deployment yml file.

**Comment by graemerocher** [comment]
Thanks for the feedback, we will look into improving this
