### ISSUE TITLE
Missing dependency io.micronaut:http-server-netty:1.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by jeremyrempel** [micronaut-projects/micronaut-examples#2]
git clone https://github.com/micronaut-projects/micronaut-examples
$ cd hello-world-kotlin
$ ./gradlew run

* What went wrong:
Execution failed for task ':kaptGenerateStubsKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find io.micronaut:http-server-netty:1.0.0-SNAPSHOT.
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/io/micronaut/http-server-netty/1.0.0-SNAPSHOT/maven-metadata.xml
         https://repo.maven.apache.org/maven2/io/micronaut/http-server-netty/1.0.0-SNAPSHOT/http-server-netty-1.0.0-SNAPSHOT.pom
         https://repo.maven.apache.org/maven2/io/micronaut/http-server-netty/1.0.0-SNAPSHOT/http-server-netty-1.0.0-SNAPSHOT.jar
         file:/Users/jrempel/.m2/repository/io/micronaut/http-server-netty/1.0.0-SNAPSHOT/maven-metadata.xml
         file:/Users/jrempel/.m2/repository/io/micronaut/http-server-netty/1.0.0-SNAPSHOT/http-server-netty-1.0.0-SNAPSHOT.pom
         file:/Users/jrempel/.m2/repository/io/micronaut/http-server-netty/1.0.0-SNAPSHOT/http-server-netty-1.0.0-SNAPSHOT.jar
     Required by:
         project :
   > Could not find io.micronaut:runtime:1.0.0-SNAPSHOT.
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/io/micronaut/runtime/1.0.0-SNAPSHOT/maven-metadata.xml
         https://repo.maven.apache.org/maven2/io/micronaut/runtime/1.0.0-SNAPSHOT/runtime-1.0.0-SNAPSHOT.pom
         https://repo.maven.apache.org/maven2/io/micronaut/runtime/1.0.0-SNAPSHOT/runtime-1.0.0-SNAPSHOT.jar
         file:/Users/jrempel/.m2/repository/io/micronaut/runtime/1.0.0-SNAPSHOT/maven-metadata.xml
         file:/Users/jrempel/.m2/repository/io/micronaut/runtime/1.0.0-SNAPSHOT/runtime-1.0.0-SNAPSHOT.pom
         file:/Users/jrempel/.m2/repository/io/micronaut/runtime/1.0.0-SNAPSHOT/runtime-1.0.0-SNAPSHOT.jar
     Required by:
         project :

**Comment by graemerocher** [comment]
Micronaut has not yet been released, so you need to build it from source. See the instructions at https://github.com/micronaut-projects/micronaut-core/blob/master/README.md

Thanks for trying Micronaut!

**Comment by abcfy2** [comment]
By the way, when the Micronaut will be released ?

**Comment by graemerocher** [comment]
First milestone will be released next week

**Comment by graemerocher** [comment]
The examples are now runnable without building from source using snapshot builds for the moment.
