### ISSUE TITLE
@Value not expanded correctly in spock tests

### ISSUE THREAD

**Issue by marcpa00** [micronaut-projects/micronaut-examples#22]
@Value annotation does not expand from value of properties defined in application yaml file.

See modifications I made to reproduce the problem
https://github.com/marcpa00/micronaut-examples/tree/marcpa00-value-annotation-groovy 

In hello-world-java my modified test passes, in hello-world-groovy, it does not.

(an inline diff should be available at https://github.com/micronaut-projects/micronaut-examples/compare/master...marcpa00:marcpa00-value-annotation-groovy?expand=1)

**Comment by marcpa00** [comment]
Strictly speaking, this is not really an issue on micronaut-examples, but on micronaut itself : should I raise an issue there instead ?

**Comment by graemerocher** [comment]
Yes better in the micronaut issue tracker
