### ISSUE TITLE
Tests should run against a random open port

### ISSUE THREAD

**Issue by fbricon** [micronaut-projects/micronaut-examples#34]
I have a server running on port 8080 on my machine. When building hello-world-java, this makes the HelloControllerTest test fail because the port is occupied. Tests should run on a random open port instead.

**Comment by graemerocher** [comment]
You can achieve this by removing the `micronaut.server.port` setting from `application.yml`. The default behaviour of Micronaut is to start on port 8080 when run as an application and start on a random port when started in a test, but only when `micronaut.server.port` is not explicitly set.

**Comment by fbricon** [comment]
@graemerocher yeah I understand you can do stuff like that, but from a new user perspective, I think it should work OOTB. So I think either:
- the examples should have the `micronaut.server.port` bits removed from application.yml
- tests should be documented to explain how to handle port conflicts
- there should be a specific application.yml for the tests, which fixes this issue (if it makes sense and doesn't introduce much duplication)

**Comment by graemerocher** [comment]
I updated the example to remove the hard coded port

**Comment by fbricon** [comment]
@graemerocher thanks. Does it make sense to also remove it from https://github.com/micronaut-projects/micronaut-examples/blob/8ce9469e2eac4e8949cf3f980b2a3495532c6d0b/websocket-chat/src/main/resources/application.yml#L11 and https://github.com/micronaut-projects/micronaut-examples/blob/03d47f5a993d418f73bc1292d6e4ebb056783905/hello-world-groovy/src/main/resources/application.groovy#L9

**Comment by graemerocher** [comment]
Yes I will look at removing those
