### ISSUE TITLE
Update examples to use micronaut 1.0.2

### ISSUE THREAD

**Issue by fbricon** [micronaut-projects/micronaut-examples#35]
... so that annotation processing support work properly in Eclipse-based IDEs (including [VS Code](https://github.com/redhat-developer/vscode-java/issues/693))

**Comment by graemerocher** [comment]
It will be 1.0.3 since we just released that 😄

**Comment by fbricon** [comment]
My bad, I only saw 1.0.2 when I looked at Maven central.

**Comment by graemerocher** [comment]
Yeah hasn't synced yet
