### ISSUE TITLE
Debugging Micronaut App with IntelliJ Issue

### ISSUE THREAD

**Issue by jobinesh** [micronaut-projects/micronaut-examples#76]
I created a simple Micronaut Java application by following the tutorial  given here : https://guides.micronaut.io/creating-your-first-micronaut-app/guide/index.html
When I tired debugging this app with IntelliJ, its not breaking at all at the break point that is set on the controller class method. Would like to know what is missing here.
- Java : 11
- IntelliJ IDEA 2018.3.6 (Ultimate Edition)

**Comment by gaojinlei** [comment]
@jobinesh I am using micronaut with koltin and maven. There's a solution works for me . Run application with maven command 'mn:run -Dmn.debug=true'. It will be start the application with remote debugger. You can use 'Attach debugger' to debug your code directly in the run console with intellij idea 2020.2, or you can add a new remote debugger run  configuration with yourself too. And you can see more infomations about micronaut maven plugin on https://micronaut-projects.github.io/micronaut-maven-plugin/latest/run-mojo.html

**Comment by graemerocher** [comment]
Please ask questions here https://github.com/micronaut-projects/micronaut-core/discussions
